// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by UnitySpec (https://github.com/UnitySpec).
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.PlayModeTests.Features
{
    using UnitySpec;
    using System;
    using System.Linq;

    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Example")]
    public partial class ExampleFeature
    {
        private static string[] featureTags = ((string[])(null));
        [UnityEngine.TestTools.UnityTestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 plus 1")]
        public System.Collections.IEnumerator _1Plus1()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            UnitySpec.ScenarioInfo scenarioInfo = new UnitySpec.ScenarioInfo("1 plus 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
                yield return ((System.Collections.IEnumerator)(testRunner.Given("a=1", (string)(null), (UnitySpec.Table)null, "Given ")));
#line 8
                yield return ((System.Collections.IEnumerator)(testRunner.And("b=1", (string)(null), (UnitySpec.Table)null, "And ")));
#line 9
                yield return ((System.Collections.IEnumerator)(testRunner.When("I add a and b", (string)(null), (UnitySpec.Table)null, "When ")));
#line 10
                yield return ((System.Collections.IEnumerator)(testRunner.Then("the sum should be 2", (string)(null), (UnitySpec.Table)null, "Then ")));
            }

            this.ScenarioCleanup();
        }

        private UnitySpec.ITestRunner testRunner;
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public void FeatureSetup()
        {
            testRunner = UnitySpec.TestRunnerManager.GetTestRunner(null, 0);
            featureInfo = new UnitySpec.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Users/speelbarrow/Code/Unity/MGS2025/Assets/Tests/PlayModeTests/Features", "Example", "  In order to demonstrate the usage of Cucumber testing\n  As a developer\n  I need to write an example feature file", ProgrammingLanguage.CSharp, featureTags);
        }

        public System.Collections.IEnumerator UnityOneTimeSetup()
        {
            yield return testRunner.OnFeatureStart(featureInfo);
        }

        [UnityEngine.TestTools.UnitySetUpAttribute()]
        public System.Collections.IEnumerator TestInitialize()
        {
            if (!initialized)
            {
                initialized = true;
                yield return UnityOneTimeSetup();
            }
        }

        [UnityEngine.TestTools.UnityTearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public void ScenarioInitialize(UnitySpec.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }

        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }

        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        private UnitySpec.FeatureInfo featureInfo;
        private bool initialized = false;
    }
}
#pragma warning restore
#endregion
